monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
  monolog:
    channels: [ 'application', 'deprecation']
    handlers:
      main:
        type: rotating_file
        path: "%kernel.logs_dir%/system.log"
        level: debug
        channels: [ "!event","!application"]
        max_files: 365
        formatter: monolog.formatter.application
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]
      deprecation:
        level: debug
        type: rotating_file
        path: '%kernel.logs_dir%/deprecation.log'
        channels: [ 'deprecation' ]
        max_files: 365
        formatter: monolog.formatter.application
      application:
        level: debug
        type: rotating_file
        path: '%kernel.logs_dir%/application.log'
        channels: [ 'application' ]
        max_files: 365
        formatter: monolog.formatter.application



when@prod:
  monolog:
    channels: [ 'application', 'deprecation']
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: rotating_file
        path: "%kernel.logs_dir%/system.log"
        level: debug
        channels: [ "!event","!application" ]
        max_files: 365
        formatter: monolog.formatter.application
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]
      deprecation:
        level: debug
        type: rotating_file
        path: '%kernel.logs_dir%/deprecation.log'
        channels: [ 'deprecation' ]
        max_files: 365
        formatter: monolog.formatter.application
      application:
        level: debug
        type: rotating_file
        path: '%kernel.logs_dir%/application.log'
        channels: [ 'application' ]
        max_files: 365
        formatter: monolog.formatter.application



when@test:
  monolog:
    channels: [ 'application', 'deprecation']
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event" ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
